server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    add_header Content-Type application/json;
    return 200 '{"status":"UP"}';
  }

  location = /readiness {
    add_header Content-Type application/json;
    return 200 '{"status":"READY"}';
  }

  location = /livez {
    add_header Content-Type application/json;
    return 200 '{"status":"UP"}';
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}