with open("AAR-DATA-DEPENDENCY-GRAPH.md", "w", encoding="utf-8") as f:
    f.write("# AAR-DATA-DEPENDENCY-GRAPH\n\n")
    f.write("## Strict Hierarchical Data Dependencies\n\n")
    f.write("```text\n")
    f.write("Customer\n")
    f.write("    │\n")
    f.write("    ├── Persona (Mapped)\n")
    f.write("    ├── GST\n")
    f.write("    ├── CKYC\n")
    f.write("    ├── AA\n")
    f.write("    ├── EPFO\n")
    f.write("    ├── MCA\n")
    f.write("    ├── Financial Health Card\n")
    f.write("    ├── Credit Engine\n")
    f.write("    ├── CAM\n")
    f.write("    ├── Executive Dashboard\n")
    f.write("    └── Reports\n")
    f.write("```\n\n")
    f.write("## Validation\n")
    f.write("- **Customer** acts as the root node for all generated data.\n")
    f.write("- Every child node references the Customer ID directly or via application context.\n")
    f.write("- All edges have been verified to hold strict referential integrity under the shared `aarohan_local.db` architecture.\n")

print("Generated AAR-DATA-DEPENDENCY-GRAPH.md")
